# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventinstance',
            options={'ordering': ['start_date']},
        ),
    ]
