# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni_wagtail_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetailpage',
            name='repeat',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
